# Generated by Django 6.0.2 on 2026-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0002_cellule_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepartement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=60)),
                ('sexe', models.CharField(choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=15)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
