# Generated by Django 6.0.2 on 2026-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0003_departement_membre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='celluel',
            new_name='cellule',
        ),
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
