# Generated by Django 6.0.2 on 2026-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0004_rename_celluel_profil_cellule_membre_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='sexeUser',
            field=models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=15, null=True),
        ),
    ]
