# Generated by Django 6.0.2 on 2026-02-21 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0005_profil_sexeuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eglise.departement'),
        ),
        migrations.AddField(
            model_name='membre',
            name='province',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='userMembre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
