# Generated by Django 6.0.2 on 2026-02-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0007_typecotisation_cotisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='etatCivil',
            field=models.CharField(choices=[('marie', 'Marie'), ('celibateur', 'Celibateur'), ('veuve', 'Veuve'), ('divorce', 'Divorce')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='dateCotisation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='userCotisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
