# Generated by Django 6.0.2 on 2026-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0008_membre_etatcivil_alter_cotisation_datecotisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='deces',
            field=models.CharField(default='non', max_length=30, null=True),
        ),
    ]
