# Generated by Django 6.0.2 on 2026-02-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0009_membre_deces'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='typeM',
            field=models.CharField(default='membre', max_length=30, null=True),
        ),
    ]
