# Generated by Django 6.0.2 on 2026-02-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0010_membre_typem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='devise',
            field=models.CharField(choices=[('cdf', 'Cdf'), ('usd', 'Usd')], default='cdf', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='membreCotisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eglise.membre'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='cotisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eglise.typecotisation'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='etatCivil',
            field=models.CharField(choices=[('marie', 'Marie'), ('celibateur', 'Celibateur'), ('veuve', 'Veuve'), ('divorce', 'Divorce'), ('veuf', 'Veuf')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEvenement', models.CharField(max_length=50)),
                ('dateEvenement', models.DateField()),
                ('userEvenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
