# Generated by Django 6.0.2 on 2026-02-22 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0011_cotisation_devise_cotisation_membrecotisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMateriel', models.CharField(max_length=50, null=True)),
                ('etatMateriel', models.CharField(choices=[('tres bon', 'Tres Bon'), ('bon', 'Bon'), ('panne', 'Panne')], max_length=30, null=True)),
                ('dateRegister', models.DateField(auto_now_add=True)),
                ('quantiteMateriel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePermission', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutB', models.CharField(choices=[('active', 'Active'), ('bloque', 'Bloque')], max_length=15)),
                ('userBloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutP', models.CharField(default='oui', max_length=3, null=True)),
                ('datePermission', models.DateField()),
                ('userPermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eglise.typepermission')),
            ],
        ),
    ]
