# Generated by Django 6.0.2 on 2026-02-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0013_materiel_usermateriel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motifDepense', models.CharField(max_length=50)),
                ('montantDepense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deviseDepense', models.CharField(choices=[('cdf', 'Cdf'), ('usd', 'Usd')], max_length=30)),
                ('dateDepense', models.DateField()),
                ('dateAutoDep', models.DateField(auto_now_add=True)),
                ('userDepense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
