# Generated by Django 6.0.2 on 2026-03-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0014_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCommune', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eglise.commune'),
        ),
    ]
